### ISSUE TITLE
Cant delete loot History

### ISSUE THREAD

**Issue by micheldewit** [Anonomit/LootReserve#16]
Issue: When selecting in the LootReserve Host folder, I cannot wipe my LootReserve Loot History. I only can add them to the blacklist to get them removed from the recent Loot History. 
LootReserve Version: LootReserve-2022-10-10 
WoWVersion: WoTLK Classic. 
![This](https://user-images.githubusercontent.com/1338656/210864581-f24bfb5d-0874-4f66-b79a-99ae32d8c884.png)

**Comment by Anonomit** [comment]
Your screenshot is of the Recent Loot list. You can shift-click an item instead of using ctrl-click and this will remove it from the list without blacklisting it.
