### ISSUE TITLE
/roll 100 for MS and /roll 99 for offspec

### ISSUE THREAD

**Issue by luttman** [Anonomit/LootReserve#19]
I like this addon way more than the big competitor Gar*ul

Would it be able to add the same feature of roll 100 for MS and roll 99 for OS.

it's mostly to make the loot to be done quicker. 

BR LuttmaN

**Comment by Anonomit** [comment]
This is now a feature as of today with c5c93a357d90739348f1e2cfc6bcf148d12c492e.
