### ISSUE TITLE
Questions about the Addon

### ISSUE THREAD

**Issue by Sulan2** [Anonomit/LootReserve#20]
Hi ive been doing a lot of raid leading with this addon and here is some things im wondering about

This is for Lootreserve in WOTLK

1. The addon doesnt seem to remove winners SR from the loot table but I feel like it used to do this earlier, im not sure if I have disabled this somewhere

2. How does the the addon count Multireserves? 
Lets say a player with 3xSR on a Tier token in ICC win a token after 1 roll, does that mean they still have 2 SR left?
If they instead would have used 3 rolls to win the item that means they have 0 SR left or?

The addon doesnt seem to keep track of this so I have to do it manually at the same time

3. How do I add extra loot people can SR, like Shadowfrost shards and Saronites in ICC? 
Ive tried adding it in Edited Loot but it doesnt then show up when people can pick items they want and it doesnt work to link either

**Comment by Anonomit** [comment]
1. It's possible you've changed the setting for this. You can find the Host settings by clicking the cogwheel at the top of the Host window. By default, the addon does remove reserves from players who win items. If it's set to remove reserves and still isn't doing that, then it's a bug.

2. This is configurable. You can set it so winning an item removes one of the winner's reserves, all of their reserves on that item, or none at all. If someone is allowed multiple rolls, it doesn't matter which of the rolls wins - only that the person has won and may now have reserves removed. The default setting tries to infer whether you'd want to allow a person to keep any reserves on an item after winning it. The tooltip when selecting the option has a brief description of how it works, but you can always change it to consistently remove 0, 1, or all reserves.

3. Editing the loot should reveal them to reservers. The items are supposed to show up in the Reserves window, and are reservable through chat. I haven't been able to reproduce this issue, so it may be that you may have a corrupted settings file or something. Try making a similar change to show hidden items in some other raid that you've never customized. If you still can't get it to work for ICC then it's probably a bug and I'd like to take a look at your SavedVariables file for LootReserve to see if I can patch the addon to fix that issue. Let me know if that's the case and I can help you find the settings files if you don't know where they're stored.

**Comment by Sulan2** [comment]
Yeah u were rigt about 1 and 2, must have disabled this someway without noticing.

About 3

![LR4](https://github.com/Anonomit/LootReserve/assets/86251944/43a41780-4342-4541-a414-47c8da9605de)

![LR1](https://github.com/Anonomit/LootReserve/assets/86251944/f7e6e961-e175-4152-b606-083f873e7839)

![LR2](https://github.com/Anonomit/LootReserve/assets/86251944/05aceb6b-e7c9-40e2-8a86-2254968f72cb)


Ive tried to add Crusader Orb in Trial of the Crusader and it doesnt work either

**Comment by Anonomit** [comment]
Okay, I see the issue. Those items are already in those raids, and they're hidden by default. When editing loot, browse to a category where the item exists and unhide it from there. I guess I should probably prevent items that already exist from being added as Custom Loot.

**Comment by Sulan2** [comment]
Thanks it worked in ICC but Crusader Orb in ToC doesnt appear anywhere

as a last question.. Would it be possible for this addon to work with the website softres.it?

The people who plays on my current server are all used to another addon so raid leading with Lootreserve without everyone else not having it downloaded can be really tough.

There is an addon called Gargul that can import the reserves from this website and it would be great if this addon could also import the info the same way

**Comment by Anonomit** [comment]
Crusader Orb shows up in the Tribute Chest. I guess it should appear in all boss loot tables though.

LootReserve has actually always worked with the CSV export from Softresit pretty much since they both came out in 2020. I've noted the compatibility in curseforge description just now since it wasn't mentioned anywhere.

**Comment by Anonomit** [comment]
Oh I remember why this is weird. I only have it listed for the 10m chest, and that appears to be correct. But it also drops from bosses in 25m and not 10m, which I missed. I'll make these changes.

**Comment by Sulan2** [comment]
Can you elaborate how this addon works with CSV Export? What exactly do I do to import it into the addon etc?

**Comment by Anonomit** [comment]
I've added a more visible Import/Export button to the main tab of the Host window, so this should be easier to find. You can import from Softres.it if you use that site, and you can export your session or roll history from the same place.
