### ISSUE TITLE
SoD: Set pieces tied to the incorrect token

### ISSUE THREAD

**Issue by AaronPena1** [Anonomit/LootReserve#22]
**Describe the bug**
In SoD, some set pieces are tied to the wrong token, causing issues if trying to reserve the item will reserve the incorrect token.

**To Reproduce**
1. Open the Loot Reserve Window, click on `Set Pieces`.
2. Scroll down to the `Electromantic Grounding Sabatons` and `Electromantic Chauses` items and see that the boots are flagged as coming from the leg token, and the legs coming from the boots token.
3. This also affects reserves as reserving the item directly will reserve the wrong token.

**Expected behavior**

1. The Set Pieces list shows the right tokens for the give items
2. Reserving a set piece will reserve the correct token for that slot.

**Screenshots**

![image](https://github.com/Anonomit/LootReserve/assets/5281325/8b45fd83-e40b-46e5-95cf-05d05cc1e4be)

**Version:**
- WoW Version: SoD 1.15.1.53623
 - Addon Version: 2024-03-16

**Additional context**

**Comment by Anonomit** [comment]
Thank you! Fixed in ebf62d573ef0b49c3ae1df5c691e41763edbf84c.
