### ISSUE TITLE
Can't reserve items in Throne of the Four Winds.

### ISSUE THREAD

**Issue by Cabro** [Anonomit/LootReserve#25]
**Describe the bug**
The items with random suffixes cannot be reserved. You are getting error stating "this item can't be reserved".

**To Reproduce**
1 - try to reserve any of the random suffix items from To4W.

**Expected behavior**
You should be able to reserve those items.

**Screenshots**
![image](https://github.com/Anonomit/LootReserve/assets/1155017/1487aa8c-287e-4045-9fcb-c37d0c28df32)

**Version:**
- WoW Cataclysm
 - Addon Version 2024-05-23

**Additional context**

**Comment by Anonomit** [comment]
Thanks for the report. Releasing the fix now.
