### ISSUE TITLE
"Reset stages" doesn't actually do anything.

### ISSUE THREAD

**Issue by Cabro** [Anonomit/LootReserve#29]
**Describe the bug**
After confirming i want to reset the roll stages, nothing changes when i open the "Roll for:" window later, all the roll stages are still enabled. There should only be the default ones (Main spec, offspec, looks etc).

**To Reproduce**
1. Go to Lootreserve Host
2. Click on "Add..." new roll stages. Add as many as you like and enable them.
3. Go to "Reset". Confirm in the popup you want to reset them.
4. Notice all custom roll stages are still enabled.

**Expected behavior**
There should only be the default ones (Main spec, offspec, looks etc).
After confirm, you still have all the old ones - check 3rd and 4th option, that is after reset.

**Screenshots**
![image](https://github.com/Anonomit/LootReserve/assets/1155017/b5ec1caf-e345-473d-aadc-f3cead91cfd4)
![image](https://github.com/Anonomit/LootReserve/assets/1155017/bdf85cc4-d027-4369-800e-f3db51b8c194)

**Version:**
- WoW cata
 - Addon 2024-06-04

**Additional context**

**Comment by Anonomit** [comment]
Thanks for the catch. This reset button is actually resetting the list of stages, but it isn't clearing the currently active stages. So you would still need to deselect any custom stages you activated after doing the reset.

This is unintuitive and unintentional, and I'll fix it to revert the active stages back to the default list as well.
