### ISSUE TITLE
Tiered rolls (same highest roll) don't offer a proper way to deal with it when End Automatically is enabled.

### ISSUE THREAD

**Issue by Cabro** [Anonomit/LootReserve#30]
**Describe the bug**
Last raid i came to this situation when highest rolls were the same. However i didn't have any option to "solve the tie" or was there any further announce from the addon that there was a tie. It simply came to a halt.

**To Reproduce**
1. Have 2 players roll the same highest roll. (which is what i tried to do with the adding a custom roll "stage" so we get there sooner by having to only roll between 5 numbers, not 100, but it seems there is no option for that in the addon).
2. Have End Automatically.
3. There is no "Solve tie" option.

**Expected behavior**
Should have the "Solve tie" option when you have End Automatically checked.

**Screenshots**
Sadly, don't have video or screenshots.

**Version:**
- WoW cata
 - Addon 2024-06-04

**Additional context**

**Comment by Anonomit** [comment]
Good point, I'll change it so that tie rolls are never ended automatically.
