### ISSUE TITLE
Export history can break CSV pattern and format

### ISSUE THREAD

**Issue by dkdirekt** [Anonomit/LootReserve#31]
**Describe the bug**
Export history with "," default delimiter is breaking pattern due to "," in some item names. 
Example: https://www.wowhead.com/classic/item=19364/ashkandi-greatsword-of-the-brotherhood

**Version:**
- WoW Version: v1.15.4 (b56857) [ERA:SOD]
 - Addon Version: 2024-10-03

**Possible workaround**
Change delimiter from "," to ";" seems to be a good way.

**Comment by Anonomit** [comment]
Thanks for the report. I chose to put double quotes around item names with commas.
