### ISSUE TITLE
Please add a release tag & zip file named like ____________-bc.zip so that addon managers like wowup.io can be used instead of curse

### ISSUE THREAD

**Issue by mspk7305** [Anonomit/LootReserve#7]
Please add a release tag & zip file named like ____________-bc.zip so that addon managers like wowup.io can be used instead of curse

**Comment by Anonomit** [comment]
Done. I saw your reddit post the other day and do plan to check out some alternative hosting sites. I've been using WowUp as well and I'm disappointed with Curseforge's decision to restrict the API.
